from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from pydantic import BaseModel
import anthropic
from app.core.database import get_db
from app.core.dependencies import get_current_user
from app.models.user import User
from app.models.playlist import Playlist
from app.models.mood_log import MoodLog
from app.services import spotify, claude

router = APIRouter(prefix="/moodmix", tags=["moodmix"])


class MoodRequest(BaseModel):
    mood: str


@router.post("/generate")
async def generate_moodmix(
    request: MoodRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict:
    try:
        queries = claude.get_moodmix_queries(request.mood)
    except anthropic.BadRequestError:
        raise HTTPException(status_code=402, detail="Anthropic API credits required. Please add credits at console.anthropic.com.")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Claude error: {str(e)}")

    track_uris = []
    track_names = []
    for query in queries:
        results = await spotify.search_tracks(current_user.access_token, query)
        if results:
            track = results[0]
            track_uris.append(track["uri"])
            track_names.append(f"{track['name']} - {track['artists'][0]['name']}")

    if not track_uris:
        raise HTTPException(status_code=404, detail="No tracks found for this mood")

    playlist_name = f"MoodMix: {request.mood.title()}"
    playlist_data = await spotify.create_playlist(
        current_user.access_token,
        current_user.spotify_id,
        playlist_name,
        description=f"Generated by MoodMix for the mood: {request.mood}",
    )

    await spotify.add_tracks_to_playlist(
        current_user.access_token,
        playlist_data["id"],
        track_uris,
    )

    playlist = Playlist(
        user_id=current_user.id,
        spotify_playlist_id=playlist_data["id"],
        name=playlist_name,
        mood_input=request.mood,
        feature="moodmix",
    )
    db.add(playlist)
    db.flush()

    mood_log = MoodLog(
        user_id=current_user.id,
        mood_input=request.mood,
        playlist_id=playlist.id,
    )
    db.add(mood_log)
    db.commit()

    return {
        "playlist_id": playlist_data["id"],
        "playlist_url": playlist_data["external_urls"]["spotify"],
        "name": playlist_name,
        "tracks": track_names,
    }
