import json
import random
import string
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.core.dependencies import get_current_user
from app.models.user import User
from app.models.room import Room
from app.models.room_member import RoomMember
from app.models.playlist import Playlist
from app.services import spotify, claude

router = APIRouter(prefix="/partydj", tags=["partydj"])


def generate_room_code() -> str:
    return "".join(random.choices(string.ascii_uppercase + string.digits, k=6))


@router.post("/rooms")
async def create_room(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict:
    code = generate_room_code()
    room = Room(code=code, host_user_id=current_user.id)
    db.add(room)
    db.flush()

    top_artists_data = await spotify.get_top_artists(current_user.access_token)
    top_genres = list({g for a in top_artists_data for g in a.get("genres", [])})

    member = RoomMember(
        room_id=room.id,
        user_id=current_user.id,
        top_genres=json.dumps(top_genres[:10]),
    )
    db.add(member)
    db.commit()

    return {"room_id": room.id, "code": code}


@router.post("/rooms/{code}/join")
async def join_room(
    code: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict:
    room = db.query(Room).filter(Room.code == code, Room.status == "waiting").first()
    if not room:
        raise HTTPException(status_code=404, detail="Room not found or already started")

    existing = db.query(RoomMember).filter(
        RoomMember.room_id == room.id,
        RoomMember.user_id == current_user.id,
    ).first()
    if existing:
        return {"room_id": room.id, "code": code, "message": "Already in room"}

    top_artists_data = await spotify.get_top_artists(current_user.access_token)
    top_genres = list({g for a in top_artists_data for g in a.get("genres", [])})

    member = RoomMember(
        room_id=room.id,
        user_id=current_user.id,
        top_genres=json.dumps(top_genres[:10]),
    )
    db.add(member)
    db.commit()

    return {"room_id": room.id, "code": code}


@router.post("/rooms/{code}/generate")
async def generate_partydj(
    code: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict:
    room = db.query(Room).filter(Room.code == code).first()
    if not room:
        raise HTTPException(status_code=404, detail="Room not found")
    if room.host_user_id != current_user.id:
        raise HTTPException(status_code=403, detail="Only the host can generate the playlist")

    members = db.query(RoomMember).filter(RoomMember.room_id == room.id).all()
    members_genres = [json.loads(m.top_genres) for m in members if m.top_genres]

    queries = claude.get_partydj_playlist(members_genres)

    track_uris = []
    track_names = []
    for query in queries:
        results = await spotify.search_tracks(current_user.access_token, query)
        if results:
            track = results[0]
            track_uris.append(track["uri"])
            track_names.append(f"{track['name']} - {track['artists'][0]['name']}")

    playlist_name = f"PartyDJ — Room {code}"
    playlist_data = await spotify.create_playlist(
        current_user.access_token,
        current_user.spotify_id,
        playlist_name,
        description=f"Group playlist generated by PartyDJ for room {code}",
    )

    await spotify.add_tracks_to_playlist(
        current_user.access_token,
        playlist_data["id"],
        track_uris,
    )

    room.status = "done"
    room.spotify_playlist_id = playlist_data["id"]

    playlist = Playlist(
        user_id=current_user.id,
        spotify_playlist_id=playlist_data["id"],
        name=playlist_name,
        feature="partydj",
    )
    db.add(playlist)
    db.commit()

    return {
        "playlist_id": playlist_data["id"],
        "playlist_url": playlist_data["external_urls"]["spotify"],
        "name": playlist_name,
        "tracks": track_names,
        "member_count": len(members),
    }
